### ISSUE TITLE
|----4位闰月|-------13位1为30天 0为29 是什么意思

### ISSUE THREAD

**Issue by FFMRyan** [isee15/Lunar-Solar-Calendar-Converter#10]
|----4位闰月|-------13位1为30天 0为29 是什么意思

**Comment by isee15** [comment]
>>> bin(0xca57)
'0110 0 1 0 1 0 0 1 0 1 0 1 1 1'
0110闰月6月
0 1 0 1 0 0 1 0 1 0 1 1 1 
代表从1-13月(包含闰月) 0 29天，1 30天
所以1月29天 2月30天 3月29天 4月30天。。。
也可以看convert.html里面的转换
