### ISSUE TITLE
Tried on 2017-01-04, the lunarMonth is 14.

### ISSUE THREAD

**Issue by compext** [isee15/Lunar-Solar-Calendar-Converter#11]
Calendar c = Calendar.getInstance();
Solar solar = new Solar();
solar.solarYear = 2017;
solar.solarMonth = Calendar.JANUARY;
solar.solarDay = 4;
Lunar lunar = LunarSolarConverter.SolarToLunar(solar);

**Comment by isee15** [comment]
is Java Version ？
use Demo.java
{solarDay=4,solarMonth=1,solarYear=2017}
{isleap=false,lunarDay=7,lunarMonth=12,lunarYear=2016}
{solarDay=4,solarMonth=1,solarYear=2017}
乙未年

**Comment by isee15** [comment]
I know why.
`In java.util.Calendar, January is defined as month 0, not month 1`

**Comment by compext** [comment]
and GanZhi is also incorrect, 2017-02-04 should be 丁酉

**Comment by isee15** [comment]
System.out.println(LunarSolarConverter.lunarYearToGanZhi(2015)); 
 just not modify Demo case
