### ISSUE TITLE
Python 版本的阴历转阳历 显示结果怎么看？

### ISSUE THREAD

**Issue by hsiunien** [isee15/Lunar-Solar-Calendar-Converter#14]
converter = LunarSolarConverter()
    lolar = Lunar(1998, 2, 3, isleap=True)
    solar = converter.LunarToSolar(lolar)
    pprint('%s-%s-%s' % (solar.solarYear, solar.solarMonth, solar.solarDay))
    print("Done")

输出
' 1998.4838136092799-2.9047222222161952--0.01999999999998181'
这是阳历的几月几号呢？

**Comment by isee15** [comment]
在python2中 int/int的返回值是int，但是在python3中，对于int/int 返回值是float。所以转换有问题。我更新一下

**Comment by isee15** [comment]
// maps to __floordiv__, which should return the floored result of /
使用// 代替 / 执行int的除法，兼容python3
