### ISSUE TITLE
阳历2018年三月份数据转换有问题

### ISSUE THREAD

**Issue by arronwy** [isee15/Lunar-Solar-Calendar-Converter#15]
from LunarSolarConverter.LunarSolarConverter import LunarSolarConverter, Lunar, Solar

converter = LunarSolarConverter()

solar = Solar(2018, 2, 28)
print(vars(solar))
lunar = converter.SolarToLunar(solar)
print(vars(lunar))

solar = Solar(2018, 3, 1)
print(vars(solar))
lunar = converter.SolarToLunar(solar)
print(vars(lunar))

Output:
{'solarDay': 28, 'solarMonth': 2, 'solarYear': 2018}
{'isleap': False, 'lunarDay': 13, 'lunarMonth': 1, 'lunarYear': 2018}
{'solarDay': 1, 'solarMonth': 3, 'solarYear': 2018}
{'isleap': False, 'lunarDay': 22, 'lunarMonth': 2, 'lunarYear': 2018}

**Comment by arronwy** [comment]
问题环境是Python 3.6.3:
3.6.3 |Anaconda custom (64-bit)| (default, Oct 16 2017, 15:28:36) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

**Comment by isee15** [comment]
{'solarDay': 28, 'solarMonth': 2, 'solarYear': 2018}
{'isleap': False, 'lunarDay': 13, 'lunarMonth': 1, 'lunarYear': 2018}
{'solarDay': 1, 'solarMonth': 3, 'solarYear': 2018}
{'isleap': False, 'lunarDay': 14, 'lunarMonth': 1, 'lunarYear': 2018}

**Comment by isee15** [comment]
https://github.com/isee15/Lunar-Solar-Calendar-Converter/issues/14
使用的源码版本吗？

**Comment by arronwy** [comment]
我发现问题是由于安装时使用命令 pip install LunarSolarConverter 安装造成的，
 pip uninstall LunarSolarConverter 后下载源码，然后到Python目录：
python setup.py build
python setup.py install 之后使用就好了
还有源码里面有个：  
 ./LunarSolarConverter/check.py
 print "Check Done"
可能python3兼容需要改下

**Comment by isee15** [comment]
pypi 也更新了
