### ISSUE TITLE
如何获取干支 ？

### ISSUE THREAD

**Issue by patrickkh7788** [isee15/Lunar-Solar-Calendar-Converter#16]
使用这个库可以计算天干地支吗？

**Comment by isee15** [comment]
在java版本里面有人pull requests 给了一个干支的实现
public static String lunarYearToGanZhi(int lunarYear){
		final String[] tianGan = {"甲","乙","丙","丁","戊","己","庚","辛","壬","癸"};
		final String[] diZhi = {"子","丑","寅","卯","辰","巳","午","未","申","酉","戌","亥"};
		return tianGan[(lunarYear-4) % 10]+diZhi[(lunarYear-4) % 12]+"年";
	}

**Comment by patrickkh7788** [comment]
thanks!
