### ISSUE TITLE
Maybe too many exposed functions/variables?

### ISSUE THREAD

**Issue by RidgeSTD** [isee15/Lunar-Solar-Calendar-Converter#2]
I've read and tried to understand this repo(java version) for about a week, and I've come to that, since there are only to API for java client, why are there so many public method exposed?
I'd like to discuss about it in this issue, and there will be a new merge request from my fork in a few days. Stay in touch.

我花了大约一周时间阅读了java部分的部分代码，我发现，既然java的API只有两个方法暴露出来，为何有如此多的public方法？(几乎全部)。这可能有违设计模式。我在考虑应该修改部分为私有方法。
希望在这个issue里讨论这个问题，几天后我会推一个解决方案到我的fork上我们来看看能不能解决这个问题。

**Comment by winlandiano** [comment]
I made a stupid mistake.
