### ISSUE TITLE
以 ruby 版本測試時，輸入solar日期 2018, 1, 1，農曆日期會轉換錯誤

### ISSUE THREAD

**Issue by sikajs** [isee15/Lunar-Solar-Calendar-Converter#20]
[
@solar_year: 2018
@solar_month: 1
@solar_day: 1
]
=> #<Lunar:0x00007fa5749c6640 @lunar_year=2018, @lunar_month=1, @lunar_day=-45, @is_leap=false>

還是說在跨年度的時候必須要有自己的轉換？

**Comment by isee15** [comment]
merge了一个PR，但是里面有个笔误。。
已经fix。https://github.com/isee15/Lunar-Solar-Calendar-Converter/commit/270076f49e66b9a7123e4693b2f0198739a36a3d
