### ISSUE TITLE
conver solar to lunar js

### ISSUE THREAD

**Issue by TranHanHieu** [isee15/Lunar-Solar-Calendar-Converter#22]
i have isues covert solar to lunar, the result returned is incorrect, can you support me?

**Comment by isee15** [comment]
should paste your code sample

**Comment by TranHanHieu** [comment]
let converter = new lsconverter.LunarSolarConverter();
    let solar = new lsconverter.Lunar();
    solar.solarYear = date.getFullYear();
    solar.solarMonth = date.getMonth();
    solar.solarDay = date.getDate();
    var lunar = converter.LunarToSolar(solar);
    console.log(`${lunar.lunarMonth}/${lunar.lunarDay}/${lunar.lunarYear);

input: date = new Date();

**Comment by isee15** [comment]
let converter = new lsconverter.LunarSolarConverter();
let solar = new lsconverter.Lunar(); // why? solar = new lsconverter.Solar();
solar.solarYear = date.getFullYear();
solar.solarMonth = date.getMonth();// getMonth return from 0 to 11. so date.getMonth()+1
solar.solarDay = date.getDate();
var lunar = converter.LunarToSolar(solar);// why? var lunar = converter.SolarToLunar(solar);
console.log(`${lunar.lunarMonth}/${lunar.lunarDay}/${lunar.lunarYear);

**Comment by TranHanHieu** [comment]
I try to follow the example in check.js
