### ISSUE TITLE
Java版本完全不准确

### ISSUE THREAD

**Issue by wangwei0906** [isee15/Lunar-Solar-Calendar-Converter#23]
![image](https://user-images.githubusercontent.com/22309305/82666112-b9251080-9c67-11ea-9f1d-e76791a787d6.png)

**Comment by isee15** [comment]
建议运行一下Demo.java验证
{solarDay=10,solarMonth=10,solarYear=1994}
{isleap=false,lunarDay=6,lunarMonth=9,lunarYear=1994}
{solarDay=10,solarMonth=10,solarYear=1994}
