### ISSUE TITLE
LunarSolarConverter.class.php 计算异常

### ISSUE THREAD

**Issue by grootgordon** [isee15/Lunar-Solar-Calendar-Converter#4]
如：由公历1997-11-15 应为农历：1997-10-16

而计算为：
object(Solar)[1]
  public 'solarDay' => int 15
  public 'solarMonth' => int 11
  public 'solarYear' => int 1997
object(Lunar)[2]
  public 'isleap' => boolean false
  public 'lunarDay' => int 17
  public 'lunarMonth' => int 10
  public 'lunarYear' => int 1997
object(Solar)[3]
  public 'solarDay' => int 15
  public 'solarMonth' => int 11
  public 'solarYear' => int 1996
object(Lunar)[2]
  public 'isleap' => boolean false
  public 'lunarDay' => int 17
  public 'lunarMonth' => int 10
  public 'lunarYear' => int 1997

修复版本：
https://github.com/120991021/Lunar-Solar-Calendar-Converter/commit/7dc445e7ec5a0197f558869e52cb92206ffec8fd

@@ -75,7 +75,7 @@ public static function GetBitInt($data, $length, $shift)
     public static function SolarToInt($y, $m, $d)
     {
         $m = ($m + 9) % 12;
-        $y = intval($y - $m / 10);
-        $y = intval($y) - intval($m / 10);
       return intval(365 \* $y + intval($y / 4) - intval($y / 100) + intval($y / 400) + intval(($m \* 306 + 5) / 10) + ($d - 1));
   }

**Comment by isee15** [comment]
welcome to pull request
