### ISSUE TITLE
兄弟，oc和swift的代码在iOS8.1的真机抛异常，exc_breakpoint code=exc_arm_breakpoint subcode=0xe7ffdefe。模拟器没问题

### ISSUE THREAD

**Issue by wongben** [isee15/Lunar-Solar-Calendar-Converter#5]
兄弟，oc和swift的代码在iOS8.1的真机抛异常，exc_breakpoint code=exc_arm_breakpoint subcode=0xe7ffdefe。模拟器没问题

**Comment by isee15** [comment]
有断点在哪一行异常的吗？有可能是int溢出了

**Comment by wongben** [comment]
> 在 2015年12月9日，下午2:36，isee15 notifications@github.com 写道：
> 
> 有断点在哪一行异常的吗？
> 
> —
> 
> 我修复了^_^见附件。,是Int32位溢出了，在32位机器上会重现。90行-100行之间。OC和swift都应该有问题吧。

 class func SolarFromInt(g:Int)->Solar
    {
      let value:Float = 10000 \* Float(g) + 14780
      let result = Int(value / 3652425)
      //这里用Int会溢出
      var y = result
        var ddd = g - (365*y + y/4 - y/100 + y/400);
        if (ddd < 0)
        {

**Comment by isee15** [comment]
int overflow
