### ISSUE TITLE
generate.htm生成1-2100的数据有点问题

### ISSUE THREAD

**Issue by wxs77577** [isee15/Lunar-Solar-Calendar-Converter#8]
好像生成出了错误的格式，0x后面跟负数

![image](https://cloud.githubusercontent.com/assets/1990059/16036980/f0bfabca-3250-11e6-82ed-36fc9da34109.png)

**Comment by yuangu** [comment]
建议使用https://github.com/yuangu/sxtwl_cpp  也支持多语言版本。BC722年以后与实历相符 .python可以用pip安装。下面是例子
'''#-*-coding:utf-8-*-

import  sxtwl
lunar = sxtwl.Lunar()  #实例化日历库

ymc = [u"十一", u"十二", u"正", u"二", u"三", u"四", u"五", u"六", u"七", u"八", u"九", u"十" ]
rmc = [u"初一", u"初二", u"初三", u"初四", u"初五", u"初六", u"初七", u"初八", u"初九", u"初十",
 u"十一", u"十二", u"十三", u"十四", u"十五", u"十六", u"十七", u"十八", u"十九",
  u"二十", u"廿一", u"廿二", u"廿三", u"廿四", u"廿五", u"廿六", u"廿七", u"廿八", u"廿九", u"三十", u"卅一"]

day = lunar.getDayByLunar(2030, 3, 27)

print  u"公历:", day.y, u"年", day.m, u"月", day.d, u"日"
if day.Lleap:
    print u"阴历:润", ymc[day.Lmc], u"月", rmc[day.Ldi], u"日"
else:
    print u"阴历:", ymc[day.Lmc], u"月", rmc[day.Ldi], u"日"
'''

**Comment by isee15** [comment]
i)公元前256年（秦襄昭王52年）采用秦历，此前一直采用古周历（但春秋战国时各国历法不一，较为混乱）。秦历以十月为岁首，“后九月”为闰月。 
ii)公元前105年，西汉太初元年五月改历，以正月为岁首，该年有十五个月（从十月、十一月、十二月、一月、二月、......十二月）。 
iii)公元9年，新朝王莽始建国1年，以12月为正月（丑月），故上一年无“十二月”。 
iv)公元23年，淮阳王改元更始，复用因寅正，以地皇十一月为更始1年的十月，故是年有两个十月。 
v)三国魏青龙5年（公元237年）三月，改元景初，建丑为正，以三月为四月，四月为五月，...，十二月为正月。而景初三年十二月，魏复寅正，故是年有两个十二月。 
vi)周武则天天授一年（载初1年，公元689年）十一月，该行周历子正。以十一月为岁首，该为载初1年正月，故乙丑年只有十个月。 
vii)久视1年十月复寅正，以正月为十一月，故是年有14个月。 
viii)唐上元2年（公元761年）九月去年号，但称元年。以建子为正，月以所建辰为名，原十月称亥月，原十一月称子月（岁首），...，原三月为辰月。而建巳月复寅正，恢复原月名，仍称四月。故辛丑年无十一月、十二月。壬寅年有十四个月。 

因为农历的不连续性，所以目前支持最小765年
